Version numbers
w3c/manual-of-style pull request #13
Opened 2021-01-07 17:41 UTC by plehegar

This addresses #11 

cc @dontcallmedom  @ashimura

2021-01-07 17:43 UTC, dontcallmedom commented
paging @tidoust and @deniak since this was at least analyzed in the context of the series management

2021-01-08 05:58 UTC, deniak requested changes

2021-01-08 05:58 UTC, deniak commented on index.html
> +<p><code>Part_Number</code>, edition number, and <code>Part_Number</code>
```suggestion
<p><code>Part_Number</code>, edition number, and <code>Version_Number</code>
```

2021-01-08 07:01 UTC, deniak commented
With the work on the series, we started to store the version number as it appears in the title but there's a lack of consistency between the specs leading to different shortname strategy. For instance:
* [WebXR Hand Input Module - Level 1](https://www.w3.org/TR/webxr-hand-input-1/), shortname: `webxr-hand-input-1`, version number stored: 1
* [Personalization Semantics Content Module 1.0](https://www.w3.org/TR/personalization-semantics-content-1.0/), shortname: `personalization-semantics-content-1.0`, version number stored: 1.0
* [Representing Content in RDF 1.0](https://www.w3.org/TR/Content-in-RDF10/), shortname: `Content-in-RDF10`, version number stored: 1.0
* [Decentralized Identifiers (DIDs) v1.0](https://www.w3.org/TR/did-core/), shortname: `did-core`, version number stored: 1.0

As you can see, the version appearing in the title can affect the choice of the shortname so since `2, 2.0, 2.0.0 are equivalent`, I was wondering if we couldn't only allow the first format to avoid ambiguity. We aren't there yet, but I thinking there could be some confusion if a spec reaches a level 10+.

2021-01-08 13:47 UTC, tidoust reviewed
Not a change introduced by this PR but I had not noticed that the manual of style recommends `["Version" Version_Number]`. I'm not aware of any spec that has "Version" in its title. All titles I can think of end with the version number without any prefix. Are there examples?

If not, that does not necessarily mean that the recommendation is wrong but, at a minimum, it would not represent [current practice](https://www.w3.org/Guide/manual-of-style/#abstract)

2021-01-08 13:47 UTC, tidoust commented on index.html
> +<p><code>Part_Number</code>, edition number, and <code>Version_Number</code>
I would treat `Part_Number` and edition number separately as I would only expect integers in these cases. That is, "Groovy API Part 2" looks good but "Groovy API Part 2.3" seems wrong. Similarly, "Groovy API 2nd Edition" looks good, but not "Groovy API 2.3 Edition".

2021-01-08 21:38 UTC, swickr reviewed
LGTM

2021-01-11 11:17 UTC, SteveALee commented on index.html
> +  Each element SHOULD increase numerically. Major version one (1.y.z) is for initial development. For additional
Usually, Semantic Versioning uses 0 Major for initial development and 1 first public release. Even though we do everything in public the transition from 0 to 1 does indicate a commitment to new stability. Is that not relevant for this use?

https://semver.org/#spec-item-4
https://semver.org/#spec-item-5

2021-01-14 15:46 UTC, svgeesus commented on index.html
> +  Each element SHOULD increase numerically. Major version one (1.y.z) is for initial development. For additional
Right but there are no W3C specifications which do this. It would also break pubrules: FPWD to CR would be v0 and then the PR and Rec would be 1.0; then the next version would also be 1.0 until it moved to PR.

I think this would be super confusing.

So best to say that specification versions do not follow Semantic Versioning in this regard.

2021-01-14 15:48 UTC, SteveALee commented on index.html
> +  Each element SHOULD increase numerically. Major version one (1.y.z) is for initial development. For additional
OK - Got it
Perhaps spell it out rather than leaving it as a possible type-o?

2021-02-02 11:51 UTC, nigelmegitt commented on index.html
> +  Each element SHOULD increase numerically. Major version one (1.y.z) is for initial development. For additional
What about adopting a suffix notation on the version, so Rec would be 1.0.0, then next update might be 1.1.0[-suffix] or 2.0.0[-suffix]? This is often done on GitHub repos that use semantic versioning.

We could be clever about the suffix we use - instead of "-RC" for Release Candidate, we could put the maturity level, i.e. -WD or -CR etc. The idea is only to remove the suffix when publishing ("releasing") as a Rec.

2026-07-16 14:08 UTC, closed without merging